version: '3'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - app-network

  app:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "8080:8080"
    links:
      - db
    environment:
      - MONGO_USERNAME=user
      - MONGO_PASSWORD=pass
      - MONGO_HOST=db
      - MONGO_PORT=27017
      - MONGO_DB=marvel
    depends_on: 
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
